global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'sat-health'
    static_configs:
      - targets: ['sat-runner:8080'] # Placeholder для будущего HTTP-экспортера
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']