name: CI
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install -y shellcheck
      - run: ls -la src/linux/ src/macos/
      - run: shellcheck src/linux/*.sh --severity=error
      - run: shellcheck src/macos/*.sh --severity=error

  publish-npm:
    needs: lint
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com'
      - run: |
          npm config set @MELS-010101:registry https://npm.pkg.github.com/
          npm publish --access public
        working-directory: packaging/npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-nuget:
    needs: lint
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
      - run: dotnet pack sysadmin-toolkit.nuspec -c Release -o dist/
        working-directory: packaging/nuget
      - run: dotnet nuget push dist/*.nupkg --source "https://nuget.pkg.github.com/MELS-010101" --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate